### ISSUE TITLE
<Form> - Create form component for logging new craft

### ISSUE THREAD

**Issue by tdoran** [fac-13/craft-track#8]
Related to User Story #3

**Comment by helenzhou6** [comment]
Acceptance Criteria:
- [ ] Create a form for logging a workshop - `<Createform>`
- [ ] Create a form for logging a shoe - `<Createform>`
- [ ] `<Form>` contains `<Shoe>` / `<Workshop>` functional element
- [ ] `<Form>` has a state: whether the type is workshop or shoes -- renders the appropriate form
- [ ] The shoe `<Form>` has various states: stitch/front/back colours - and if these are updated in the form, then the states are updated and passed down to `<Shoe>` - that renders the icon appropriately
- [ ] Upon toggling the radio button completed or not, it will toggle hiding certain inputs
- [ ] Upon save, will update the local storage JSON and update the `<App>` parent state: currentpage.
